import type { Metadata } from "next";
import "./globals.css";
import AppBar from "@/components/AppBar";
import PageWrapper from "@/components/PageWrapper";
import ThemeProvider from "@/context/ThemeProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <AppBar />
            <main>
              <PageWrapper>
                {children}
              </PageWrapper>
            </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
